- hosts: all
  vars_files:
    - "variables.yml"
- name: Run root_certs playbook
  import_playbook: root_certs.yml

- name: Run certs playbook
  import_playbook: certs.yml

- name: Run control_plane playbook
  import_playbook: control_plane.yml

- name: Run workers playbook
  import_playbook: workers.yml
